apiVersion: apps/v1
kind: Deployment
metadata:
  name: payload-processing
spec:
  template:
    spec:
      serviceAccountName: payload-processing
      automountServiceAccountToken: true
      containers:
        - name: payload-processing
          imagePullPolicy: Never
