apiVersion: apps/v1
kind: Deployment
metadata:
  name: payload-processing
spec:
  template:
    spec:
      containers:
        - name: payload-processing
          env:
            - name: BODY_ORACLE_HOP_INDEX
              value: "2"
